<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="generator" content="rustdoc"><meta name="description" content="Tries to execute the given closure and catches an Objective-C exception if one is thrown."><title>catch in objc2::exception - Rust</title><script>if(window.location.protocol!=="file:")document.head.insertAdjacentHTML("beforeend","SourceSerif4-Regular-46f98efaafac5295.ttf.woff2,FiraSans-Regular-018c141bf0843ffd.woff2,FiraSans-Medium-8f9a781e4970d388.woff2,SourceCodePro-Regular-562dcc5011b6de7d.ttf.woff2,SourceCodePro-Semibold-d899c5a5c4aeb14a.ttf.woff2".split(",").map(f=>`<link rel="preload" as="font" type="font/woff2" crossorigin href="../../static.files/${f}">`).join(""))</script><link rel="stylesheet" href="../../static.files/normalize-76eba96aa4d2e634.css"><link rel="stylesheet" href="../../static.files/rustdoc-492a78a4a87dcc01.css"><meta name="rustdoc-vars" data-root-path="../../" data-static-root-path="../../static.files/" data-current-crate="objc2" data-themes="" data-resource-suffix="" data-rustdoc-version="1.82.0 (f6e511eec 2024-10-15)" data-channel="1.82.0" data-search-js="search-a99f1315e7cc5121.js" data-settings-js="settings-4313503d2e1961c2.js" ><script src="../../static.files/storage-118b08c4c78b968e.js"></script><script defer src="sidebar-items.js"></script><script defer src="../../static.files/main-921df33f47b8780c.js"></script><noscript><link rel="stylesheet" href="../../static.files/noscript-3b12f09e550e0385.css"></noscript><link rel="alternate icon" type="image/png" href="../../static.files/favicon-32x32-422f7d1d52889060.png"><link rel="icon" type="image/svg+xml" href="../../static.files/favicon-2c020d218678b618.svg"></head><body class="rustdoc fn"><!--[if lte IE 11]><div class="warning">This old browser is unsupported and will most likely display funky things.</div><![endif]--><nav class="mobile-topbar"><button class="sidebar-menu-toggle" title="show sidebar"></button></nav><nav class="sidebar"><div class="sidebar-crate"><h2><a href="../../objc2/index.html">objc2</a><span class="version">0.5.2</span></h2></div><div class="sidebar-elems"><h2><a href="index.html">In objc2::<wbr>exception</a></h2></div></nav><div class="sidebar-resizer"></div><main><div class="width-limiter"><rustdoc-search></rustdoc-search><section id="main-content" class="content"><div class="main-heading"><h1>Function <a href="../index.html">objc2</a>::<wbr><a href="index.html">exception</a>::<wbr><a class="fn" href="#">catch</a><button id="copy-path" title="Copy item path to clipboard">Copy item path</button></h1><span class="out-of-band"><a class="src" href="../../src/objc2/exception.rs.html#283-294">source</a> · <button id="toggle-all-docs" title="collapse all docs">[<span>&#x2212;</span>]</button></span></div><pre class="rust item-decl"><code>pub unsafe fn catch&lt;R&gt;(
    closure: impl <a class="trait" href="https://doc.rust-lang.org/1.82.0/core/ops/function/trait.FnOnce.html" title="trait core::ops::function::FnOnce">FnOnce</a>() -&gt; R + <a class="trait" href="https://doc.rust-lang.org/1.82.0/core/panic/unwind_safe/trait.UnwindSafe.html" title="trait core::panic::unwind_safe::UnwindSafe">UnwindSafe</a>,
) -&gt; <a class="enum" href="https://doc.rust-lang.org/1.82.0/core/result/enum.Result.html" title="enum core::result::Result">Result</a>&lt;R, <a class="enum" href="https://doc.rust-lang.org/1.82.0/core/option/enum.Option.html" title="enum core::option::Option">Option</a>&lt;<a class="struct" href="../rc/struct.Retained.html" title="struct objc2::rc::Retained">Retained</a>&lt;<a class="struct" href="struct.Exception.html" title="struct objc2::exception::Exception">Exception</a>&gt;&gt;&gt;</code></pre><details class="toggle top-doc" open><summary class="hideme"><span>Expand description</span></summary><div class="docblock"><p>Tries to execute the given closure and catches an Objective-C exception
if one is thrown.</p>
<p>This is the Objective-C equivalent of Rust’s <a href="https://doc.rust-lang.org/1.82.0/std/panic/fn.catch_unwind.html" title="fn std::panic::catch_unwind"><code>catch_unwind</code></a>.
Accordingly, if your Rust code is compiled with <code>panic=abort</code> this cannot
catch the exception.</p>
<h2 id="errors"><a class="doc-anchor" href="#errors">§</a>Errors</h2>
<p>Returns a <code>Result</code> that is either <code>Ok</code> if the closure succeeded without an
exception being thrown, or an <code>Err</code> with the exception. The exception is
automatically released.</p>
<p>The exception is <code>None</code> in the extremely exceptional case that the
exception object is <code>nil</code>. This should basically never happen, but is
technically possible on some systems with <code>@throw nil</code>, or in OOM
situations.</p>
<h2 id="safety"><a class="doc-anchor" href="#safety">§</a>Safety</h2>
<p>The given closure must not panic (e.g. normal Rust unwinding into this
causes undefined behaviour).</p>
<p>Additionally, this unwinds through the closure from Objective-C, which is
undefined behaviour until <code>C-unwind</code> is stabilized, see <a href="https://rust-lang.github.io/rfcs/2945-c-unwind-abi.html">RFC-2945</a> - you
can try this out on nightly using the <code>unstable-c-unwind</code> feature flag.</p>
</div></details></section></div></main></body></html>